export const SAVE_SALES_TOTAL_REVENUES = 'SAVE_SALES_TOTAL_REVENUES';
export const SAVE_SERVICE_BASED_REVENUES = 'SAVE_SERVICE_BASED_REVENUES';
export const SAVE_CHANNEL_BASED_REVENUES = 'SAVE_CHANNEL_BASED_REVENUES';
export const SAVE_CITY_BASED_REVENUES = 'SAVE_CITY_BASED_REVENUES';
